var configInvTemplate = {
inv_userId_routingAliasId	:	'inv_userId_routingAliasId',
inv_supplierId	:	'inv_supplierId',
inv_supplierDisplayName	:	'inv_supplierDisplayName',
inv_company_businessName	:	'inv_company_businessName',
inv_company_ABN_ACN_LC	:	'inv_company_ABN_ACN_LC',
inv_company_address_streetNumber	:	'inv_company_address_streetNumber',
inv_company_address_streetName	:	'inv_company_address_streetName',
inv_company_address_streetType	:	'inv_company_address_streetType',
inv_company_address_suburb	:	'inv_company_address_suburb',
inv_company_address_state	:	'inv_company_address_state',
inv_company_address_postcode	:	'inv_company_address_postcode',
inv_company_address_country	:	'inv_company_address_country',
inv_company_address_contact	:	'inv_company_address_contact',
inv_company_address_email	:	'inv_company_address_email',
inv_company_careOf	:	'inv_company_careOf',
inv_invoiceDate	:	'inv_invoiceDate',
inv_purchaseOrderNumber	:	'inv_purchaseOrderNumber',
inv_dateOfService	:	'inv_dateOfService',
inv_goodsOrServiceDescription	:	'inv_goodsOrServiceDescription',
inv_TAX_Percentage	:	'inv_TAX_Percentage',
inv_TAX_amount	:	'inv_TAX_amount',
inv_TAX_Exemption	:	'inv_TAX_Exemption',
inv_netAmount	:	'inv_netAmount',
inv_currency	:	'inv_currency',
inv_discount	:	'inv_discount',
inv_creditNotes	:	'inv_creditNotes',
inv_BankBSB	:	'inv_BankBSB',
inv_BankAccount	:	'inv_BankAccount',
inv_BankAccountName	:	'inv_BankAccountName',
inv_isNew	:	'inv_isNew',
inv_isPaid	:	'inv_isPaid',
inv_record_created	:	'inv_record_created',
inv_is_record_updated	:	'inv_is_record_updated',
inv_record_updated	:	'inv_record_updated'
};

module.exports = configInvTemplate;
