var configTranTemplate = {

tran_userId_routingAliasId	:	'tran_userId_routingAliasId',
tran_accountId	:	'tran_accountId',
tran_accountNicName	:	'tran_accountNicName',
tran_accountName	:	'tran_accountName',
tran_date 	:	'tran_date ',
tran_amount 	:	'tran_amount ',
tran_baseType 	:	'tran_baseType ',
tran_category 	:	'tran_category ',
tran_postDate	:	'tran_postDate',
tran_status	:	'tran_status',
tran_description 	:	'tran_description ',
tran_chequeNumber	:	'tran_chequeNumber',
tran_CoACategoryId	:	'tran_CoACategoryId',
tran_CoACategoryName	:	'tran_CoACategoryName',
tran_CoASubCategoryId	:	'tran_CoASubCategoryId',
tran_CoASubCategoryName	:	'tran_CoASubCategoryName',
tran_isManual	:	'tran_isManual',
tran_isAutoSyncRule	:	'tran_isAutoSyncRule',
tran_merchantId	:	'tran_merchantId',
tran_merchantName	:	'tran_merchantName',
tran_merchantRuleId	:	'tran_merchantRuleId',
tran_merchantRuleName	:	'tran_merchantRuleName',
tran_isNew :		'tran_isNew :',
tran_isVerified	:	'tran_isVerified',
tran_providerId	:	'tran_providerId',
tran_providerName	:	'tran_providerName',
tran_isBusinessOrPersonalExpense	:	'tran_isBusinessOrPersonalExpense',
tran_isSplitTransaction	:	'tran_isSplitTransaction',
tran_splitBusinessAmount	:	'tran_splitBusinessAmount',
tran_splitPersonalAmount	:	'tran_splitPersonalAmount',
tran_isReceiptAttached	:	'tran_isReceiptAttached',
tran_receiptURL	:	'tran_receiptURL',
tran_record_created	:	'tran_record_created',
tran_is_record_updated 	:	'tran_is_record_updated ',
tran_record_updated	:	'tran_record_updated',

};

module.exports = configTranTemplate;
