var configUserTemplate = {
	usr_uid: 'usr_uid',
	usr_displayName : 'usr_displayName',
	usr_firstName : 'usr_firstName',
	usr_familyName : 'usr_familyName',
	usr_middleName : 'usr_middleName',
	usr_emailVerified : 'usr_emailVerified',
	usr_phoneNumber: 'usr_phoneNumber',
	usr_photoURL : 'usr_photoURL',
	usr_dob : 'usr_dob',
	usr_gender : 'usr_gender',
	usr_email : 'usr_email',
  company_businessName : 'company_businessName',
	company_ABN_ACN_LC : 'company_ABN_ACN_LC'	,
	company_contact : 'company_contact',
	company__email : 'company__email',
	company_address_streetNumber : 'company_address_streetNumber',
	company_address_streetName : 'company_address_streetName',
	company_address_streetType : 'company_address_streetType',
	company_address_suburb : 'company_address_suburb',
	company_address_state : 'company_address_state',
	company_address_postcode : 'company_address_postcode',
  company_address_country : 'company_address_country',
	usr_url : 'usr_url',
	usr_locale : 'usr_locale',
	usr_currency : 'usr_currency',
	usr_isSubscritionActive : 'usr_isSubscritionActive',
	usr_isNotified: 'usr_isNotified',
	usr_subscriptionType: 'usr_subscriptionType',
	usr_subscriptionAmount : 'usr_subscriptionAmount',
	usr_subscriptionCostToDate : 'usr_subscriptionCostToDate',
	usr_subscriptionFrequency: 'usr_subscriptionFrequency',
	usr_isUserCloudConnected : 'usr_isUserCloudConnected',
	usr_isDropBox : 'usr_isDropBox',
	usr_isGoogle: 'usr_isGoogle',
	usr_isBox : 'usr_isBox',
	usr_isICloud : 'usr_isICloud',
	usr_isOneDrive : 'usr_isOneDrive',
	usr_invoicePaymentBankBSB : 'usr_invoicePaymentBankBSB',
	usr_invoicePaymentBankAccountNumber: 'usr_invoicePaymentBankAccountNumber',
	usr_invoicePaymentBankAccountName : 'usr_invoicePaymentBankAccountName',
	usr_invoicePaymentBankName : 'usr_invoicePaymentBankName'

};

module.exports = configUserTemplate;
